/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query GetEpochParticipants($streamerId: JSON) {\n  EpochParticipants(where: {streamer: {equals: $streamerId}}, limit: 50) {\n    docs {\n      id\n      roleInEpoch\n      epoch {\n        id\n        title\n        dateStart\n        dateEnd\n        squad {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n}": typeof types.GetEpochParticipantsDocument,
    "query GetEvents($streamerId: JSON) {\n  Events(\n    where: {streamersPresent: {equals: $streamerId}}\n    sort: \"-date\"\n    limit: 20\n  ) {\n    docs {\n      id\n      title\n      date\n      type\n      epoch {\n        id\n        title\n      }\n      grid {\n        id\n        title\n        type\n        cover {\n          url\n        }\n      }\n      contentBlocks {\n        ... on EventYoutube {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on EventQuote {\n          id\n          blockType\n          text\n          author\n        }\n        ... on EventReport {\n          id\n          blockType\n          title\n          htmlReport\n        }\n        ... on EventSMC {\n          id\n          blockType\n          videoSlug\n          videoId\n          videoTitle\n          caption\n        }\n      }\n    }\n  }\n}": typeof types.GetEventsDocument,
    "query GetSquadMembers($streamerId: JSON) {\n  SquadMembers(\n    where: {streamer: {equals: $streamerId}}\n    sort: \"-joinDate\"\n    limit: 20\n  ) {\n    docs {\n      id\n      role\n      joinDate\n      leaveDate\n      streamer {\n        id\n        name\n        slug\n        avatar {\n          url\n        }\n      }\n      squad {\n        id\n        name\n        slug\n        logo {\n          url\n        }\n      }\n    }\n  }\n}": typeof types.GetSquadMembersDocument,
    "query GetSquadsPage {\n  Squads(sort: \"name\", limit: 100) {\n    totalDocs\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      totalMembers: members {\n        docs {\n          id\n        }\n      }\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          streamer {\n            id\n            name\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"dateStart\") {\n        docs {\n          id\n          dateStart\n          dateEnd\n        }\n      }\n    }\n  }\n  totalEpochs: Epochs(limit: 1) {\n    totalDocs\n  }\n  totalStreamers: Streamers(limit: 1) {\n    totalDocs\n  }\n}": typeof types.GetSquadsPageDocument,
    "query GetSquadEvents($epochIds: [JSON]) {\n  Events(where: {epoch: {in: $epochIds}}, sort: \"-date\", limit: 200) {\n    docs {\n      id\n      title\n      date\n      type\n      description\n      coverImage {\n        url\n        alt\n      }\n      streamersPresent {\n        id\n        name\n        slug\n        avatar {\n          url\n          alt\n        }\n      }\n    }\n  }\n}": typeof types.GetSquadEventsDocument,
    "query GetSquadPage($slug: String) {\n  Squads(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      history\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          joinDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      pastMembers: members(where: {leaveDate: {exists: true}}) {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"-dateStart\") {\n        docs {\n          id\n          title\n          slug\n          summary\n          dateStart\n          dateEnd\n          isFeatured\n          coverImage {\n            url\n            alt\n          }\n          events {\n            docs {\n              id\n            }\n          }\n          participants {\n            docs {\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.GetSquadPageDocument,
    "query GetStreamerGrids($streamerId: JSON) {\n  StreamGrids(where: {participants__streamer: {equals: $streamerId}}) {\n    docs {\n      id\n      title\n      type\n      cover {\n        url\n        alt\n      }\n      events(where: {streamersPresent: {equals: $streamerId}}, sort: \"-date\") {\n        docs {\n          id\n          title\n          date\n          type\n          description\n          contentBlocks {\n            ... on EventYoutube {\n              id\n              blockType\n              url\n              caption\n            }\n            ... on EventQuote {\n              id\n              blockType\n              text\n              author\n            }\n            ... on EventReport {\n              id\n              blockType\n              title\n              htmlReport\n            }\n            ... on EventSMC {\n              id\n              blockType\n              videoSlug\n              videoId\n              videoTitle\n              caption\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.GetStreamerGridsDocument,
    "query GetStreamerPage($slug: String!) {\n  Streamers(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      realName\n      slug\n      nicknames {\n        id\n        nickname\n      }\n      avatar {\n        url\n      }\n      banner {\n        url\n      }\n      blocks {\n        ... on Hero {\n          id\n          blockType\n          title\n          subtitle\n        }\n        ... on YoutubeEmbed {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on Quote {\n          id\n          blockType\n          text\n          author\n        }\n      }\n      squads {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          squad {\n            id\n            name\n            slug\n            logo {\n              url\n            }\n          }\n        }\n      }\n      epochs {\n        docs {\n          id\n          roleInEpoch\n          epoch {\n            id\n            title\n            dateStart\n            dateEnd\n            squad {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.GetStreamerPageDocument,
    "query GetStreamerStats($streamerIdJson: JSON, $streamerId: Int!, $recentLimit: Int) {\n  allEvents: Events(where: {streamersPresent: {equals: $streamerIdJson}}) {\n    totalDocs\n  }\n  soloEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}, grid: {exists: false}}\n  ) {\n    totalDocs\n  }\n  recentEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}}\n    sort: \"-date\"\n    limit: $recentLimit\n  ) {\n    docs {\n      id\n      title\n      date\n    }\n  }\n  gridCounts: GridCounts(streamerId: $streamerId) {\n    marathon\n    tournament\n    series\n    collab\n    festival\n  }\n}": typeof types.GetStreamerStatsDocument,
};
const documents: Documents = {
    "query GetEpochParticipants($streamerId: JSON) {\n  EpochParticipants(where: {streamer: {equals: $streamerId}}, limit: 50) {\n    docs {\n      id\n      roleInEpoch\n      epoch {\n        id\n        title\n        dateStart\n        dateEnd\n        squad {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n}": types.GetEpochParticipantsDocument,
    "query GetEvents($streamerId: JSON) {\n  Events(\n    where: {streamersPresent: {equals: $streamerId}}\n    sort: \"-date\"\n    limit: 20\n  ) {\n    docs {\n      id\n      title\n      date\n      type\n      epoch {\n        id\n        title\n      }\n      grid {\n        id\n        title\n        type\n        cover {\n          url\n        }\n      }\n      contentBlocks {\n        ... on EventYoutube {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on EventQuote {\n          id\n          blockType\n          text\n          author\n        }\n        ... on EventReport {\n          id\n          blockType\n          title\n          htmlReport\n        }\n        ... on EventSMC {\n          id\n          blockType\n          videoSlug\n          videoId\n          videoTitle\n          caption\n        }\n      }\n    }\n  }\n}": types.GetEventsDocument,
    "query GetSquadMembers($streamerId: JSON) {\n  SquadMembers(\n    where: {streamer: {equals: $streamerId}}\n    sort: \"-joinDate\"\n    limit: 20\n  ) {\n    docs {\n      id\n      role\n      joinDate\n      leaveDate\n      streamer {\n        id\n        name\n        slug\n        avatar {\n          url\n        }\n      }\n      squad {\n        id\n        name\n        slug\n        logo {\n          url\n        }\n      }\n    }\n  }\n}": types.GetSquadMembersDocument,
    "query GetSquadsPage {\n  Squads(sort: \"name\", limit: 100) {\n    totalDocs\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      totalMembers: members {\n        docs {\n          id\n        }\n      }\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          streamer {\n            id\n            name\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"dateStart\") {\n        docs {\n          id\n          dateStart\n          dateEnd\n        }\n      }\n    }\n  }\n  totalEpochs: Epochs(limit: 1) {\n    totalDocs\n  }\n  totalStreamers: Streamers(limit: 1) {\n    totalDocs\n  }\n}": types.GetSquadsPageDocument,
    "query GetSquadEvents($epochIds: [JSON]) {\n  Events(where: {epoch: {in: $epochIds}}, sort: \"-date\", limit: 200) {\n    docs {\n      id\n      title\n      date\n      type\n      description\n      coverImage {\n        url\n        alt\n      }\n      streamersPresent {\n        id\n        name\n        slug\n        avatar {\n          url\n          alt\n        }\n      }\n    }\n  }\n}": types.GetSquadEventsDocument,
    "query GetSquadPage($slug: String) {\n  Squads(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      history\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          joinDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      pastMembers: members(where: {leaveDate: {exists: true}}) {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"-dateStart\") {\n        docs {\n          id\n          title\n          slug\n          summary\n          dateStart\n          dateEnd\n          isFeatured\n          coverImage {\n            url\n            alt\n          }\n          events {\n            docs {\n              id\n            }\n          }\n          participants {\n            docs {\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n}": types.GetSquadPageDocument,
    "query GetStreamerGrids($streamerId: JSON) {\n  StreamGrids(where: {participants__streamer: {equals: $streamerId}}) {\n    docs {\n      id\n      title\n      type\n      cover {\n        url\n        alt\n      }\n      events(where: {streamersPresent: {equals: $streamerId}}, sort: \"-date\") {\n        docs {\n          id\n          title\n          date\n          type\n          description\n          contentBlocks {\n            ... on EventYoutube {\n              id\n              blockType\n              url\n              caption\n            }\n            ... on EventQuote {\n              id\n              blockType\n              text\n              author\n            }\n            ... on EventReport {\n              id\n              blockType\n              title\n              htmlReport\n            }\n            ... on EventSMC {\n              id\n              blockType\n              videoSlug\n              videoId\n              videoTitle\n              caption\n            }\n          }\n        }\n      }\n    }\n  }\n}": types.GetStreamerGridsDocument,
    "query GetStreamerPage($slug: String!) {\n  Streamers(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      realName\n      slug\n      nicknames {\n        id\n        nickname\n      }\n      avatar {\n        url\n      }\n      banner {\n        url\n      }\n      blocks {\n        ... on Hero {\n          id\n          blockType\n          title\n          subtitle\n        }\n        ... on YoutubeEmbed {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on Quote {\n          id\n          blockType\n          text\n          author\n        }\n      }\n      squads {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          squad {\n            id\n            name\n            slug\n            logo {\n              url\n            }\n          }\n        }\n      }\n      epochs {\n        docs {\n          id\n          roleInEpoch\n          epoch {\n            id\n            title\n            dateStart\n            dateEnd\n            squad {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n}": types.GetStreamerPageDocument,
    "query GetStreamerStats($streamerIdJson: JSON, $streamerId: Int!, $recentLimit: Int) {\n  allEvents: Events(where: {streamersPresent: {equals: $streamerIdJson}}) {\n    totalDocs\n  }\n  soloEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}, grid: {exists: false}}\n  ) {\n    totalDocs\n  }\n  recentEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}}\n    sort: \"-date\"\n    limit: $recentLimit\n  ) {\n    docs {\n      id\n      title\n      date\n    }\n  }\n  gridCounts: GridCounts(streamerId: $streamerId) {\n    marathon\n    tournament\n    series\n    collab\n    festival\n  }\n}": types.GetStreamerStatsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetEpochParticipants($streamerId: JSON) {\n  EpochParticipants(where: {streamer: {equals: $streamerId}}, limit: 50) {\n    docs {\n      id\n      roleInEpoch\n      epoch {\n        id\n        title\n        dateStart\n        dateEnd\n        squad {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetEpochParticipants($streamerId: JSON) {\n  EpochParticipants(where: {streamer: {equals: $streamerId}}, limit: 50) {\n    docs {\n      id\n      roleInEpoch\n      epoch {\n        id\n        title\n        dateStart\n        dateEnd\n        squad {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetEvents($streamerId: JSON) {\n  Events(\n    where: {streamersPresent: {equals: $streamerId}}\n    sort: \"-date\"\n    limit: 20\n  ) {\n    docs {\n      id\n      title\n      date\n      type\n      epoch {\n        id\n        title\n      }\n      grid {\n        id\n        title\n        type\n        cover {\n          url\n        }\n      }\n      contentBlocks {\n        ... on EventYoutube {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on EventQuote {\n          id\n          blockType\n          text\n          author\n        }\n        ... on EventReport {\n          id\n          blockType\n          title\n          htmlReport\n        }\n        ... on EventSMC {\n          id\n          blockType\n          videoSlug\n          videoId\n          videoTitle\n          caption\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetEvents($streamerId: JSON) {\n  Events(\n    where: {streamersPresent: {equals: $streamerId}}\n    sort: \"-date\"\n    limit: 20\n  ) {\n    docs {\n      id\n      title\n      date\n      type\n      epoch {\n        id\n        title\n      }\n      grid {\n        id\n        title\n        type\n        cover {\n          url\n        }\n      }\n      contentBlocks {\n        ... on EventYoutube {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on EventQuote {\n          id\n          blockType\n          text\n          author\n        }\n        ... on EventReport {\n          id\n          blockType\n          title\n          htmlReport\n        }\n        ... on EventSMC {\n          id\n          blockType\n          videoSlug\n          videoId\n          videoTitle\n          caption\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetSquadMembers($streamerId: JSON) {\n  SquadMembers(\n    where: {streamer: {equals: $streamerId}}\n    sort: \"-joinDate\"\n    limit: 20\n  ) {\n    docs {\n      id\n      role\n      joinDate\n      leaveDate\n      streamer {\n        id\n        name\n        slug\n        avatar {\n          url\n        }\n      }\n      squad {\n        id\n        name\n        slug\n        logo {\n          url\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetSquadMembers($streamerId: JSON) {\n  SquadMembers(\n    where: {streamer: {equals: $streamerId}}\n    sort: \"-joinDate\"\n    limit: 20\n  ) {\n    docs {\n      id\n      role\n      joinDate\n      leaveDate\n      streamer {\n        id\n        name\n        slug\n        avatar {\n          url\n        }\n      }\n      squad {\n        id\n        name\n        slug\n        logo {\n          url\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetSquadsPage {\n  Squads(sort: \"name\", limit: 100) {\n    totalDocs\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      totalMembers: members {\n        docs {\n          id\n        }\n      }\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          streamer {\n            id\n            name\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"dateStart\") {\n        docs {\n          id\n          dateStart\n          dateEnd\n        }\n      }\n    }\n  }\n  totalEpochs: Epochs(limit: 1) {\n    totalDocs\n  }\n  totalStreamers: Streamers(limit: 1) {\n    totalDocs\n  }\n}"): (typeof documents)["query GetSquadsPage {\n  Squads(sort: \"name\", limit: 100) {\n    totalDocs\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      totalMembers: members {\n        docs {\n          id\n        }\n      }\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          streamer {\n            id\n            name\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"dateStart\") {\n        docs {\n          id\n          dateStart\n          dateEnd\n        }\n      }\n    }\n  }\n  totalEpochs: Epochs(limit: 1) {\n    totalDocs\n  }\n  totalStreamers: Streamers(limit: 1) {\n    totalDocs\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetSquadEvents($epochIds: [JSON]) {\n  Events(where: {epoch: {in: $epochIds}}, sort: \"-date\", limit: 200) {\n    docs {\n      id\n      title\n      date\n      type\n      description\n      coverImage {\n        url\n        alt\n      }\n      streamersPresent {\n        id\n        name\n        slug\n        avatar {\n          url\n          alt\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetSquadEvents($epochIds: [JSON]) {\n  Events(where: {epoch: {in: $epochIds}}, sort: \"-date\", limit: 200) {\n    docs {\n      id\n      title\n      date\n      type\n      description\n      coverImage {\n        url\n        alt\n      }\n      streamersPresent {\n        id\n        name\n        slug\n        avatar {\n          url\n          alt\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetSquadPage($slug: String) {\n  Squads(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      history\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          joinDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      pastMembers: members(where: {leaveDate: {exists: true}}) {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"-dateStart\") {\n        docs {\n          id\n          title\n          slug\n          summary\n          dateStart\n          dateEnd\n          isFeatured\n          coverImage {\n            url\n            alt\n          }\n          events {\n            docs {\n              id\n            }\n          }\n          participants {\n            docs {\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetSquadPage($slug: String) {\n  Squads(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      slug\n      logo {\n        url\n        alt\n      }\n      banner {\n        url\n        alt\n      }\n      history\n      currentMembers: members(where: {leaveDate: {exists: false}}) {\n        docs {\n          id\n          role\n          joinDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      pastMembers: members(where: {leaveDate: {exists: true}}) {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          streamer {\n            id\n            name\n            slug\n            avatar {\n              url\n              alt\n            }\n          }\n        }\n      }\n      epochs(sort: \"-dateStart\") {\n        docs {\n          id\n          title\n          slug\n          summary\n          dateStart\n          dateEnd\n          isFeatured\n          coverImage {\n            url\n            alt\n          }\n          events {\n            docs {\n              id\n            }\n          }\n          participants {\n            docs {\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetStreamerGrids($streamerId: JSON) {\n  StreamGrids(where: {participants__streamer: {equals: $streamerId}}) {\n    docs {\n      id\n      title\n      type\n      cover {\n        url\n        alt\n      }\n      events(where: {streamersPresent: {equals: $streamerId}}, sort: \"-date\") {\n        docs {\n          id\n          title\n          date\n          type\n          description\n          contentBlocks {\n            ... on EventYoutube {\n              id\n              blockType\n              url\n              caption\n            }\n            ... on EventQuote {\n              id\n              blockType\n              text\n              author\n            }\n            ... on EventReport {\n              id\n              blockType\n              title\n              htmlReport\n            }\n            ... on EventSMC {\n              id\n              blockType\n              videoSlug\n              videoId\n              videoTitle\n              caption\n            }\n          }\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetStreamerGrids($streamerId: JSON) {\n  StreamGrids(where: {participants__streamer: {equals: $streamerId}}) {\n    docs {\n      id\n      title\n      type\n      cover {\n        url\n        alt\n      }\n      events(where: {streamersPresent: {equals: $streamerId}}, sort: \"-date\") {\n        docs {\n          id\n          title\n          date\n          type\n          description\n          contentBlocks {\n            ... on EventYoutube {\n              id\n              blockType\n              url\n              caption\n            }\n            ... on EventQuote {\n              id\n              blockType\n              text\n              author\n            }\n            ... on EventReport {\n              id\n              blockType\n              title\n              htmlReport\n            }\n            ... on EventSMC {\n              id\n              blockType\n              videoSlug\n              videoId\n              videoTitle\n              caption\n            }\n          }\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetStreamerPage($slug: String!) {\n  Streamers(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      realName\n      slug\n      nicknames {\n        id\n        nickname\n      }\n      avatar {\n        url\n      }\n      banner {\n        url\n      }\n      blocks {\n        ... on Hero {\n          id\n          blockType\n          title\n          subtitle\n        }\n        ... on YoutubeEmbed {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on Quote {\n          id\n          blockType\n          text\n          author\n        }\n      }\n      squads {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          squad {\n            id\n            name\n            slug\n            logo {\n              url\n            }\n          }\n        }\n      }\n      epochs {\n        docs {\n          id\n          roleInEpoch\n          epoch {\n            id\n            title\n            dateStart\n            dateEnd\n            squad {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetStreamerPage($slug: String!) {\n  Streamers(where: {slug: {equals: $slug}}, limit: 1) {\n    docs {\n      id\n      name\n      realName\n      slug\n      nicknames {\n        id\n        nickname\n      }\n      avatar {\n        url\n      }\n      banner {\n        url\n      }\n      blocks {\n        ... on Hero {\n          id\n          blockType\n          title\n          subtitle\n        }\n        ... on YoutubeEmbed {\n          id\n          blockType\n          url\n          caption\n        }\n        ... on Quote {\n          id\n          blockType\n          text\n          author\n        }\n      }\n      squads {\n        docs {\n          id\n          role\n          joinDate\n          leaveDate\n          squad {\n            id\n            name\n            slug\n            logo {\n              url\n            }\n          }\n        }\n      }\n      epochs {\n        docs {\n          id\n          roleInEpoch\n          epoch {\n            id\n            title\n            dateStart\n            dateEnd\n            squad {\n              id\n              name\n              slug\n            }\n          }\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetStreamerStats($streamerIdJson: JSON, $streamerId: Int!, $recentLimit: Int) {\n  allEvents: Events(where: {streamersPresent: {equals: $streamerIdJson}}) {\n    totalDocs\n  }\n  soloEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}, grid: {exists: false}}\n  ) {\n    totalDocs\n  }\n  recentEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}}\n    sort: \"-date\"\n    limit: $recentLimit\n  ) {\n    docs {\n      id\n      title\n      date\n    }\n  }\n  gridCounts: GridCounts(streamerId: $streamerId) {\n    marathon\n    tournament\n    series\n    collab\n    festival\n  }\n}"): (typeof documents)["query GetStreamerStats($streamerIdJson: JSON, $streamerId: Int!, $recentLimit: Int) {\n  allEvents: Events(where: {streamersPresent: {equals: $streamerIdJson}}) {\n    totalDocs\n  }\n  soloEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}, grid: {exists: false}}\n  ) {\n    totalDocs\n  }\n  recentEvents: Events(\n    where: {streamersPresent: {equals: $streamerIdJson}}\n    sort: \"-date\"\n    limit: $recentLimit\n  ) {\n    docs {\n      id\n      title\n      date\n    }\n  }\n  gridCounts: GridCounts(streamerId: $streamerId) {\n    marathon\n    tournament\n    series\n    collab\n    festival\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;