/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    streamers: Streamer;
    events: Event;
    squads: Squad;
    epochs: Epoch;
    reviews: Review;
    'stream-grids': StreamGrid;
    'squad-members': SquadMember;
    'epoch-participants': EpochParticipant;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    streamers: {
      squads: 'squad-members';
      epochs: 'epoch-participants';
    };
    squads: {
      members: 'squad-members';
      epochs: 'epochs';
    };
    epochs: {
      participants: 'epoch-participants';
      events: 'events';
    };
    'stream-grids': {
      events: 'events';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    streamers: StreamersSelect<false> | StreamersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    squads: SquadsSelect<false> | SquadsSelect<true>;
    epochs: EpochsSelect<false> | EpochsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'stream-grids': StreamGridsSelect<false> | StreamGridsSelect<true>;
    'squad-members': SquadMembersSelect<false> | SquadMembersSelect<true>;
    'epoch-participants': EpochParticipantsSelect<false> | EpochParticipantsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streamers".
 */
export interface Streamer {
  id: number;
  name: string;
  slug: string;
  realName?: string | null;
  nicknames?:
    | {
        nickname: string;
        id?: string | null;
      }[]
    | null;
  biography?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  avatar?: (number | null) | Media;
  /**
   * Картинка-постер для шапки. Желательно соотношение ~21:9 или 16:9, минимальный размер 1600×720. Будет обрезана и скруглена.
   */
  banner?: (number | null) | Media;
  theme?: ('archive' | 'creator' | 'esports') | null;
  streamerVisualConfig?: {
    profileLayout?: ('bento' | 'fullwidth-timeline' | 'classic-wiki') | null;
    cardStyle?: ('clean-card' | 'chaos-glitch' | 'brutal-flat' | 'retro-box') | null;
    vibeAccent?: ('default' | 'danger' | 'legendary' | 'muted') | null;
  };
  blocks?:
    | (
        | {
            title?: string | null;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            url?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'youtubeEmbed';
          }
        | {
            text?: string | null;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  squads?: {
    docs?: (number | SquadMember)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  epochs?: {
    docs?: (number | EpochParticipant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squad-members".
 */
export interface SquadMember {
  id: number;
  streamer: number | Streamer;
  squad: number | Squad;
  role?: ('leader' | 'core' | 'secondary' | 'ex-member') | null;
  joinDate?: string | null;
  leaveDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squads".
 */
export interface Squad {
  id: number;
  name: string;
  slug: string;
  logo: number | Media;
  /**
   * Баннер сквада. Рекомендуется соотношение 21:9 или 16:9.
   */
  banner?: (number | null) | Media;
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  members?: {
    docs?: (number | SquadMember)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  epochs?: {
    docs?: (number | Epoch)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epochs".
 */
export interface Epoch {
  id: number;
  title: string;
  slug: string;
  /**
   * 1-2 предложения для превью на карточке таймлайна
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  accentColor: 'default' | 'legendary' | 'neon' | 'crimson';
  highlightEvent?: (number | null) | Event;
  isFeatured?: boolean | null;
  squad: number | Squad;
  dateStart: string;
  dateEnd?: string | null;
  participants?: {
    docs?: (number | EpochParticipant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  date: string;
  /**
   * 1-2 предложения: что случилось, почему это важно. Показывается в карточке таймлайна как превью.
   */
  description?: string | null;
  type: 'stream' | 'trip' | 'tournament' | 'collab' | 'announcement';
  epoch: number | Epoch;
  /**
   * Оставь пустым если это одиночный стрим
   */
  grid?: (number | null) | StreamGrid;
  /**
   * Кто присутствовал на этом событии
   */
  streamersPresent?: (number | Streamer)[] | null;
  eventUiConfig?: {
    layoutTemplate?: ('retro-marathon' | 'chaos-incident' | 'clean-stream' | 'brutal-alert') | null;
    eventVibe?: ('normal' | 'highlight' | 'alert' | 'muted') | null;
  };
  contentBlocks?:
    | (
        | {
            url: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventYoutube';
          }
        | {
            text: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventQuote';
          }
        | {
            title?: string | null;
            htmlReport?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventReport';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stream-grids".
 */
export interface StreamGrid {
  id: number;
  title: string;
  slug: string;
  type: 'marathon' | 'tournament' | 'series' | 'collab' | 'festival';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dateStart?: string | null;
  dateEnd?: string | null;
  cover?: (number | null) | Media;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Стримеры, состоящие в этой сетке. Если стример не в списке — сетка НЕ покажется у него на странице.
   */
  participants?:
    | {
        streamer: number | Streamer;
        role: 'organizer' | 'headliner' | 'participant' | 'guest';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epoch-participants".
 */
export interface EpochParticipant {
  id: number;
  epoch: number | Epoch;
  streamer: number | Streamer;
  roleInEpoch: 'legend' | 'core-member' | 'secondary' | 'guest' | 'ex-member';
  styleStrategy?: ('inherit-epoch' | 'force-personal-style') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  title: string;
  author?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  attachedTo: 'to-streamer' | 'to-epoch' | 'to-event';
  streamerLink?: (number | null) | Streamer;
  epochLink?: (number | null) | Epoch;
  eventLink?: (number | null) | Event;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'streamers';
        value: number | Streamer;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'squads';
        value: number | Squad;
      } | null)
    | ({
        relationTo: 'epochs';
        value: number | Epoch;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'stream-grids';
        value: number | StreamGrid;
      } | null)
    | ({
        relationTo: 'squad-members';
        value: number | SquadMember;
      } | null)
    | ({
        relationTo: 'epoch-participants';
        value: number | EpochParticipant;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streamers_select".
 */
export interface StreamersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  realName?: T;
  nicknames?:
    | T
    | {
        nickname?: T;
        id?: T;
      };
  biography?: T;
  avatar?: T;
  banner?: T;
  theme?: T;
  streamerVisualConfig?:
    | T
    | {
        profileLayout?: T;
        cardStyle?: T;
        vibeAccent?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        youtubeEmbed?:
          | T
          | {
              url?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              id?: T;
              blockName?: T;
            };
      };
  squads?: T;
  epochs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  type?: T;
  epoch?: T;
  grid?: T;
  streamersPresent?: T;
  eventUiConfig?:
    | T
    | {
        layoutTemplate?: T;
        eventVibe?: T;
      };
  contentBlocks?:
    | T
    | {
        eventYoutube?:
          | T
          | {
              url?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        eventQuote?:
          | T
          | {
              text?: T;
              author?: T;
              id?: T;
              blockName?: T;
            };
        eventReport?:
          | T
          | {
              title?: T;
              htmlReport?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squads_select".
 */
export interface SquadsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  banner?: T;
  history?: T;
  members?: T;
  epochs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epochs_select".
 */
export interface EpochsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  coverImage?: T;
  accentColor?: T;
  highlightEvent?: T;
  isFeatured?: T;
  squad?: T;
  dateStart?: T;
  dateEnd?: T;
  participants?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  content?: T;
  attachedTo?: T;
  streamerLink?: T;
  epochLink?: T;
  eventLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stream-grids_select".
 */
export interface StreamGridsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  dateStart?: T;
  dateEnd?: T;
  cover?: T;
  events?: T;
  participants?:
    | T
    | {
        streamer?: T;
        role?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "squad-members_select".
 */
export interface SquadMembersSelect<T extends boolean = true> {
  streamer?: T;
  squad?: T;
  role?: T;
  joinDate?: T;
  leaveDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epoch-participants_select".
 */
export interface EpochParticipantsSelect<T extends boolean = true> {
  epoch?: T;
  streamer?: T;
  roleInEpoch?: T;
  styleStrategy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}